[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'kovisoft/slimv'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
hook_source = '''
  let g:mkdp_auto_start = 1
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'rking/ag.vim'
