[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
  set hidden
  let g:racer_cmd = "/home/tomoyat1/.cargo/bin/racer"
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
hook_source = '''
  let g:deoplete#sources#rust#racer_binary='/home/tomoyat1/.cargo/bin/racer'
  let g:deoplete#sources#rust#rust_source_path='/home/tomoyat1/src/rust/rust/src'
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

#[[plugins]]
#repo = 'parsonsmatt/intero-neovim'
#on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_source = '''
    let g:jsx_ext_required = 0
'''
